version: '3.8'

services:
  postgres:
    image: postgres:17
    container_name: ecommerce_postgres
    environment:
      POSTGRES_DB: ecommerce_service
      POSTGRES_USER: dev_user
      POSTGRES_PASSWORD: DevSecurePass2024!
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data: 